# Generated by Django 5.1.2 on 2025-03-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="salary_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
