# Generated by Django 5.1.2 on 2025-03-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_job_salary_max_job_salary_min"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="requirements",
            field=models.TextField(blank=True),
        ),
    ]
