# Generated by Django 5.1.2 on 2025-03-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_job_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed"), ("draft", "Draft")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
